import type { Metadata } from "next";
import { Nunito, Roboto_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import "@radix-ui/themes/styles.css";
import Sidebar from "./Components/Sidebar/Sidebar";
import { auth } from "@clerk/nextjs/server";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  //variable: '--font-nunito',
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  //variable: '--font-roboto-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const {userId} = auth()
  
  return (
    <ClerkProvider>
    <html lang="en" className={`${nunito.className}`}>
      <body className="flex items-start">
      
      <Sidebar />
      <header>
            <SignedOut>
              <SignInButton />
            </SignedOut>
            <SignedIn>
              <UserButton />
            </SignedIn>
          </header>
        <main>
          {children}</main>
      </body>
    </html>
    </ClerkProvider>

  );
}
