import type { Metadata } from "next";
import { Nunito, Roboto_Mono } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import Sidebar from "./Components/Sidebar/Sidebar";

const nunito = Nunito({
  subsets: ["latin"],
  display: "swap",
  //variable: '--font-nunito',
});

const roboto_mono = Roboto_Mono({
  subsets: ["latin"],
  display: "swap",
  //variable: '--font-roboto-mono',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${nunito.className}`}>
      <body className="flex items-start justify-between">
        <Sidebar />
        <main className="w-full h-full">{children}</main>
      </body>
    </html>
  );
}
